### PR TITLE
docs: add architecture diagram for FlytePropeller plugins

### PR DESCRIPTION
**Pull request by jasonlai1218**
- Add FlytePropeller plugins architecture  image file

https://github.com/flyteorg/flyte/pull/4661 depends on this

### CODE REVIEW

**Comment by Future-Outlier** [comment]
don't merge this PR, I am discussing with @jasonlai1218 
We will change some part of it.

**Comment by Future-Outlier** [comment]
Type of handlers.
image

**Review by Future-Outlier — APPROVED** [review]
LGTM

**Review by Future-Outlier — APPROVED** [review]
LGTM

**Comment by hamersaw** [comment]
Is the purpose of this graphic (and subsequent docs) to explain that webAPI plugins call an external service, the PodPlugin creates a k8s Pod, and other plugins create k8s resource that are then executed by k8s operator deployments? IMO much of this information is duplicated from the other graphic on this page - I'm wondering if we can present more succinctly.

**Comment by Future-Outlier** [comment]
> Is the purpose of this graphic (and subsequent docs) to explain that webAPI plugins call an external service, the PodPlugin creates a k8s Pod, and other plugins create k8s resource that are then executed by k8s operator deployments? IMO much of this information is duplicated from the other graphic on this page - I'm wondering if we can present more succinctly.

Hi, thanks for your review, do you think this one is more succinctly?
image

**Comment by jasonlai1218** [comment]
@hamersaw @Future-Outlier 
I updated the picture to make it more succinct.

**Review by Future-Outlier — APPROVED** [review]
LGTM, cc @pingsutw

**Review by pingsutw — APPROVED** [review]

**Pull request merged**
